//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI_Projekat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceSRB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSRB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCI_Projekat.ResourceSRB", typeof(ResourceSRB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj korisnika.
        /// </summary>
        internal static string Broj_korisnika {
            get {
                return ResourceManager.GetString("Broj korisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rad sa administratorima.
        /// </summary>
        internal static string btn_AMF_WorkWIthAdmins {
            get {
                return ResourceManager.GetString("btn_AMF_WorkWIthAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rad sa kampovima.
        /// </summary>
        internal static string btn_AMF_WorkWIthCamps {
            get {
                return ResourceManager.GetString("btn_AMF_WorkWIthCamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rad sa volonterima.
        /// </summary>
        internal static string btn_AMF_WorkWIthVolonters {
            get {
                return ResourceManager.GetString("btn_AMF_WorkWIthVolonters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasporedi u kamp.
        /// </summary>
        internal static string btn_AVTK_RasporediUKamp {
            get {
                return ResourceManager.GetString("btn_AVTK_RasporediUKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloguj se.
        /// </summary>
        internal static string btn_Login_Login {
            get {
                return ResourceManager.GetString("btn_Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj korisnika kampa.
        /// </summary>
        internal static string btn_VWWKK_DodajKorisnikaKampa {
            get {
                return ResourceManager.GetString("btn_VWWKK_DodajKorisnikaKampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni korisnika kampa.
        /// </summary>
        internal static string btn_VWWKK_IzmijeniKorisnikaKampa {
            get {
                return ResourceManager.GetString("btn_VWWKK_IzmijeniKorisnikaKampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi korisnika kampa.
        /// </summary>
        internal static string btn_VWWKK_ObrisiKorisnikaKampa {
            get {
                return ResourceManager.GetString("btn_VWWKK_ObrisiKorisnikaKampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj admina.
        /// </summary>
        internal static string btn_WWA_DodajAdmina {
            get {
                return ResourceManager.GetString("btn_WWA_DodajAdmina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni admina.
        /// </summary>
        internal static string btn_WWA_IzmijeniAdmina {
            get {
                return ResourceManager.GetString("btn_WWA_IzmijeniAdmina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi admina.
        /// </summary>
        internal static string btn_WWA_ObrisiAdmina {
            get {
                return ResourceManager.GetString("btn_WWA_ObrisiAdmina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni kamp.
        /// </summary>
        internal static string btn_WWC_IzmijeniKamp {
            get {
                return ResourceManager.GetString("btn_WWC_IzmijeniKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj kamp.
        /// </summary>
        internal static string btn_WWC_KreirajKamp {
            get {
                return ResourceManager.GetString("btn_WWC_KreirajKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi kamp.
        /// </summary>
        internal static string btn_WWC_ObrisiKamp {
            get {
                return ResourceManager.GetString("btn_WWC_ObrisiKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj volontera.
        /// </summary>
        internal static string btn_WWV_DodajVolontera {
            get {
                return ResourceManager.GetString("btn_WWV_DodajVolontera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni volontera.
        /// </summary>
        internal static string btn_WWV_IzmijeniVolontera {
            get {
                return ResourceManager.GetString("btn_WWV_IzmijeniVolontera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi volontera.
        /// </summary>
        internal static string btn_WWV_ObrisiVolontera {
            get {
                return ResourceManager.GetString("btn_WWV_ObrisiVolontera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasporedi u kamp.
        /// </summary>
        internal static string btn_WWV_RasporediUKamp {
            get {
                return ResourceManager.GetString("btn_WWV_RasporediUKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rodjenja.
        /// </summary>
        internal static string Datum_rodjenja {
            get {
                return ResourceManager.GetString("Datum rodjenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolazak.
        /// </summary>
        internal static string Dolazak {
            get {
                return ResourceManager.GetString("Dolazak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drzava.
        /// </summary>
        internal static string Drzava {
            get {
                return ResourceManager.GetString("Drzava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drzavljanstvo.
        /// </summary>
        internal static string Drzavljanstvo {
            get {
                return ResourceManager.GetString("Drzavljanstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        internal static string Grad {
            get {
                return ResourceManager.GetString("Grad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        internal static string JMB {
            get {
                return ResourceManager.GetString("JMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamp.
        /// </summary>
        internal static string Kamp {
            get {
                return ResourceManager.GetString("Kamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime.
        /// </summary>
        internal static string Korisnicko_ime {
            get {
                return ResourceManager.GetString("Korisnicko ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rad sa volonterima.
        /// </summary>
        internal static string label_AVTK_Top {
            get {
                return ResourceManager.GetString("label_AVTK_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli, zaduženi ste za kamp.
        /// </summary>
        internal static string label_VWWKK_Top {
            get {
                return ResourceManager.GetString("label_VWWKK_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rad sa administratorima.
        /// </summary>
        internal static string label_WWA_Top {
            get {
                return ResourceManager.GetString("label_WWA_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rad sa kampovima.
        /// </summary>
        internal static string label_WWC_Top {
            get {
                return ResourceManager.GetString("label_WWC_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rad sa volonterima.
        /// </summary>
        internal static string label_WWV_Top {
            get {
                return ResourceManager.GetString("label_WWV_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli, unesite podatke.
        /// </summary>
        internal static string labelTopLogin {
            get {
                return ResourceManager.GetString("labelTopLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        internal static string labelUsername {
            get {
                return ResourceManager.GetString("labelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli, .
        /// </summary>
        internal static string lbl_AMF_top {
            get {
                return ResourceManager.GetString("lbl_AMF_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjesto prebivalista.
        /// </summary>
        internal static string Mjesto_prebivalista {
            get {
                return ResourceManager.GetString("Mjesto prebivalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kampa.
        /// </summary>
        internal static string Naziv_kampa {
            get {
                return ResourceManager.GetString("Naziv kampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocisti.
        /// </summary>
        internal static string Ocisti {
            get {
                return ResourceManager.GetString("Ocisti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odlazak.
        /// </summary>
        internal static string Odlazak {
            get {
                return ResourceManager.GetString("Odlazak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol.
        /// </summary>
        internal static string Pol {
            get {
                return ResourceManager.GetString("Pol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prebivaliste.
        /// </summary>
        internal static string Prebivaliste {
            get {
                return ResourceManager.GetString("Prebivaliste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra.
        /// </summary>
        internal static string Sifra {
            get {
                return ResourceManager.GetString("Sifra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip nesrece.
        /// </summary>
        internal static string Tip_nesrece {
            get {
                return ResourceManager.GetString("Tip nesrece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaduzeni volonter.
        /// </summary>
        internal static string Zaduzeni_volonter {
            get {
                return ResourceManager.GetString("Zaduzeni volonter", resourceCulture);
            }
        }
    }
}
