//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI_Projekat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCI_Projekat.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of users.
        /// </summary>
        internal static string Broj_korisnika {
            get {
                return ResourceManager.GetString("Broj korisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with admins.
        /// </summary>
        internal static string btn_AMF_WorkWIthAdmins {
            get {
                return ResourceManager.GetString("btn_AMF_WorkWIthAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with camps.
        /// </summary>
        internal static string btn_AMF_WorkWIthCamps {
            get {
                return ResourceManager.GetString("btn_AMF_WorkWIthCamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with volunteers.
        /// </summary>
        internal static string btn_AMF_WorkWIthVolonters {
            get {
                return ResourceManager.GetString("btn_AMF_WorkWIthVolonters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule in camp.
        /// </summary>
        internal static string btn_AVTK_RasporediUKamp {
            get {
                return ResourceManager.GetString("btn_AVTK_RasporediUKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btn_Login_Login {
            get {
                return ResourceManager.GetString("btn_Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string btn_VMF_Podesavanja {
            get {
                return ResourceManager.GetString("btn_VMF_Podesavanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with camp users.
        /// </summary>
        internal static string btn_VMF_RadSaKorisnicima {
            get {
                return ResourceManager.GetString("btn_VMF_RadSaKorisnicima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add camp user.
        /// </summary>
        internal static string btn_VWWKK_DodajKorisnikaKampa {
            get {
                return ResourceManager.GetString("btn_VWWKK_DodajKorisnikaKampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit camp user.
        /// </summary>
        internal static string btn_VWWKK_IzmijeniKorisnikaKampa {
            get {
                return ResourceManager.GetString("btn_VWWKK_IzmijeniKorisnikaKampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete camp user.
        /// </summary>
        internal static string btn_VWWKK_ObrisiKorisnikaKampa {
            get {
                return ResourceManager.GetString("btn_VWWKK_ObrisiKorisnikaKampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add administrator.
        /// </summary>
        internal static string btn_WWA_DodajAdmina {
            get {
                return ResourceManager.GetString("btn_WWA_DodajAdmina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit administrator.
        /// </summary>
        internal static string btn_WWA_IzmijeniAdmina {
            get {
                return ResourceManager.GetString("btn_WWA_IzmijeniAdmina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete administrator.
        /// </summary>
        internal static string btn_WWA_ObrisiAdmina {
            get {
                return ResourceManager.GetString("btn_WWA_ObrisiAdmina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit camp.
        /// </summary>
        internal static string btn_WWC_IzmijeniKamp {
            get {
                return ResourceManager.GetString("btn_WWC_IzmijeniKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create camp.
        /// </summary>
        internal static string btn_WWC_KreirajKamp {
            get {
                return ResourceManager.GetString("btn_WWC_KreirajKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete camp.
        /// </summary>
        internal static string btn_WWC_ObrisiKamp {
            get {
                return ResourceManager.GetString("btn_WWC_ObrisiKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add volunteer.
        /// </summary>
        internal static string btn_WWV_DodajVolontera {
            get {
                return ResourceManager.GetString("btn_WWV_DodajVolontera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit volunteer.
        /// </summary>
        internal static string btn_WWV_IzmijeniVolontera {
            get {
                return ResourceManager.GetString("btn_WWV_IzmijeniVolontera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete volunteer.
        /// </summary>
        internal static string btn_WWV_ObrisiVolontera {
            get {
                return ResourceManager.GetString("btn_WWV_ObrisiVolontera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule in camp.
        /// </summary>
        internal static string btn_WWV_RasporediUKamp {
            get {
                return ResourceManager.GetString("btn_WWV_RasporediUKamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string Datum_rodjenja {
            get {
                return ResourceManager.GetString("Datum rodjenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        internal static string Dolazak {
            get {
                return ResourceManager.GetString("Dolazak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Drzava {
            get {
                return ResourceManager.GetString("Drzava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship.
        /// </summary>
        internal static string Drzavljanstvo {
            get {
                return ResourceManager.GetString("Drzavljanstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Grad {
            get {
                return ResourceManager.GetString("Grad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        internal static string JMB {
            get {
                return ResourceManager.GetString("JMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB must have exactly 13 numbers.
        /// </summary>
        internal static string JMB_mora_imati_tacno_13_brojeva {
            get {
                return ResourceManager.GetString("JMB mora imati tacno 13 brojeva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB already exists in the database.
        /// </summary>
        internal static string JMB_vec_postoji_u_bazi_podataka {
            get {
                return ResourceManager.GetString("JMB vec postoji u bazi podataka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp.
        /// </summary>
        internal static string Kamp {
            get {
                return ResourceManager.GetString("Kamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A camp with this name already exists in the database.
        /// </summary>
        internal static string Kamp_sa_ovim_nazivom_vec_postoji_u_bazi_podataka {
            get {
                return ResourceManager.GetString("Kamp sa ovim nazivom vec postoji u bazi podataka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Korisnicko_ime {
            get {
                return ResourceManager.GetString("Korisnicko ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken.
        /// </summary>
        internal static string Korisnicko_ime_je_zauzeto {
            get {
                return ResourceManager.GetString("Korisnicko ime je zauzeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with volunteers.
        /// </summary>
        internal static string label_AVTK_Top {
            get {
                return ResourceManager.GetString("label_AVTK_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings from user,.
        /// </summary>
        internal static string label_COSF_Top {
            get {
                return ResourceManager.GetString("label_COSF_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, you are responsible for the camp.
        /// </summary>
        internal static string label_VWWKK_Top {
            get {
                return ResourceManager.GetString("label_VWWKK_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an assigned camp, contact the administrator.
        /// </summary>
        internal static string label_VWWKK_Top_Negative {
            get {
                return ResourceManager.GetString("label_VWWKK_Top_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with administrators.
        /// </summary>
        internal static string label_WWA_Top {
            get {
                return ResourceManager.GetString("label_WWA_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with camps.
        /// </summary>
        internal static string label_WWC_Top {
            get {
                return ResourceManager.GetString("label_WWC_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with volunteers.
        /// </summary>
        internal static string label_WWV_Top {
            get {
                return ResourceManager.GetString("label_WWV_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, enter your information.
        /// </summary>
        internal static string labelTopLogin {
            get {
                return ResourceManager.GetString("labelTopLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string labelUsername {
            get {
                return ResourceManager.GetString("labelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, .
        /// </summary>
        internal static string lbl_AMF_top {
            get {
                return ResourceManager.GetString("lbl_AMF_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of residence.
        /// </summary>
        internal static string Mjesto_prebivalista {
            get {
                return ResourceManager.GetString("Mjesto prebivalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to click on the volunteer you want to assign to the camp.
        /// </summary>
        internal static string Morate_kliknuti_na_volontera_kojeg_zelite_rasporediti {
            get {
                return ResourceManager.GetString("Morate kliknuti na volontera kojeg zelite rasporediti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp name.
        /// </summary>
        internal static string Naziv_kampa {
            get {
                return ResourceManager.GetString("Naziv kampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete the main admin.
        /// </summary>
        internal static string Nije_moguce_obrisati_glavnog_admina {
            get {
                return ResourceManager.GetString("Nije moguce obrisati glavnog admina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete a volunteer because he is the only one in charge of the camp.
        /// </summary>
        internal static string Nije_moguce_obrisati_volontera_jer_je_jedini_zaduzen_za_kamp {
            get {
                return ResourceManager.GetString("Nije moguce obrisati volontera jer je jedini zaduzen za kamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected the camp to which you want to assign a volunteer.
        /// </summary>
        internal static string Niste_odabrali_kamp_u_koji_zelite_rasporediti_volontera {
            get {
                return ResourceManager.GetString("Niste odabrali kamp u koji zelite rasporediti volontera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not made any changes.
        /// </summary>
        internal static string Niste_unijeli_ni_jednu_promjenu {
            get {
                return ResourceManager.GetString("Niste unijeli ni jednu promjenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Ocisti {
            get {
                return ResourceManager.GetString("Ocisti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Od {
            get {
                return ResourceManager.GetString("Od", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string Odlazak {
            get {
                return ResourceManager.GetString("Odlazak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        internal static string Pogresni_podaci {
            get {
                return ResourceManager.GetString("Pogresni podaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Pol {
            get {
                return ResourceManager.GetString("Pol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence.
        /// </summary>
        internal static string Prebivaliste {
            get {
                return ResourceManager.GetString("Prebivaliste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
     
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace HCI_Projekat {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   A strongly-typed re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResourceEN_Designer {
            get {
                return ResourceManager.GetString("ResourceEN_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Sifra {
            get {
                return ResourceManager.GetString("Sifra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled.
        /// </summary>
        internal static string Sva_polja_moraju_biti_popunjena {
            get {
                return ResourceManager.GetString("Sva polja moraju biti popunjena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Tema {
            get {
                return ResourceManager.GetString("Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accident type.
        /// </summary>
        internal static string Tip_nesrece {
            get {
                return ResourceManager.GetString("Tip nesrece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully updated.
        /// </summary>
        internal static string Uspjesno_azurirano {
            get {
                return ResourceManager.GetString("Uspjesno azurirano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully added.
        /// </summary>
        internal static string Uspjesno_dodano {
            get {
                return ResourceManager.GetString("Uspjesno dodano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully deleted.
        /// </summary>
        internal static string Uspjesno_obrisano {
            get {
                return ResourceManager.GetString("Uspjesno obrisano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volunteer has been successfully assigned to camp.
        /// </summary>
        internal static string Volonter_je_uspjesno_rasporedjen {
            get {
                return ResourceManager.GetString("Volonter je uspjesno rasporedjen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned volunteer.
        /// </summary>
        internal static string Zaduzeni_volonter {
            get {
                return ResourceManager.GetString("Zaduzeni volonter", resourceCulture);
            }
        }
    }
}
